# site settings
title: "Alex Fraley"
subtitle: "Robotic Research | Test Engineer | Test Method Development & Validation | AI Simulation | "
email: "alexmfraley@gmail.com"
description: "Portfolio website showcasing selected academic and professional work, focused largely on recent contributions to the development of test methods as a robotic research engineer."
baseurl: ""  # Leave blank for GitHub Pages to work with a custom domain
url: "https://alexfraley.com"  # Your custom domain


author: "Alex Fraley"
street_address: "Washington, DC Area"
city: 
state: 
zip_code: ""
country: "United States"
phone: ""  # Optional

# social settings
# 500px_url:
# facebook_url:
github_url: "https://github.com/amfraley"
linkedin_url: "https://www.linkedin.com/in/alexmfraley/"
# github_url: 
# gitlab_url: 
# googleplus_url:
# instagram_url:
# pinterest_url:
# slack_url:
#twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed

# ✅ GitHub Pages Deployment
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 🔥 Custom Domain for GitHub Pages
domain: "alexfraley.com"

# 🔧 Collections (for projects, publications, etc.)
collections:
  projects:
    output: true
    permalink: /projects/:path/
  publications:
    output: true
    permalink: /publications/:path/
  media:
    output: true
    permalink: /media/:path/

# 📂 Image Paths (For Your 100 Photos)
image_path: "/assets/images/"